### ISSUE TITLE
db2.Query  sql: converting argument $1 type: unsupported type []interface {}, a slice of interface panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by tablecell** [issue9/orm#11]
参考文档中 [Query/Exec:] 部分的例子代码 
```
package main

import (
	"fmt"
	"github.com/issue9/orm/v5" // sqlite3    dialect
	_ "github.com/issue9/orm/v5/core"
	"github.com/issue9/orm/v5/dialect"
	"github.com/issue9/orm/v5/fetch"
	_ "github.com/issue9/orm/v5/sqlbuilder"
	_ "github.com/mattn/go-sqlite3"
	_ "time"
	//"github.com/gorilla/sessions"
)

type User struct {
	Id   int64  `orm:"name(id);ai;"`
	Name string `orm:"name(name);`
}

func (c *User) TableName() string { return "User" }

func main() {
	db2, err := orm.NewDB("./orm.db", dialect.Sqlite3("sqlite3"))

db2.Create(&User{})

	fmt.Println(err)
	azer := &User{
		Name: "issue9",
	}

	ret, err := db2.Insert(azer)

	fmt.Println(ret, err)

	data := []*User{}
	sql := "select * from user where id >=?"
	rows, err := db2.Query(sql, []interface{}{1})  
	fmt.Println(rows, err)
	r, err := fetch.Object(true, rows, &data)
	fmt.Println(r, err)
	for k, v := range data {
		fmt.Println(k, v.Name)
	}
}
```
报错 
 sql: converting argument $1 type: unsupported type []interface {}, a slice of interface 
panic: runtime error: invalid memory address or nil pointer dereference

用 
```
	rows, err := db2.Query(sql, 1)   
``` 
返回有纪录 ,但是没有字段值

**Comment by caixw** [comment]
Name string `orm:"name(name);`
这里少了个引号，导致 Name 字段在数据中的名称并非是预想的 name。而是 Name。

当然如果你的数据库也是由这段代码创建的，那么 rows, err := db2.Query(sql, 1) 是可以正确获得值的。

**Comment by tablecell** [comment]
@caixw 
```
type User struct {
	Id   int64  `orm:"name(id);ai;"`
	Name string `orm:"name(name);"`
}
...
	rows, err := db2.Query(sql,1)
```
这样查询有字段值 
但是 
```
type User struct {
	Id   int64  `orm:"name(id);ai;"`
	Name string `orm:"name(name);"`
}
...
	rows, err := db2.Query(sql,[]interface{}{1})
```
还是会报错,是不是文档没更新的原因 

另外还有一个sqlbuilder的用法
参考文档中的例子
```
// 导出 id=1 的数据
_,err := sqlbuilder.Select(e, e.Dialect()).Select("*").From("{#table}").Where("id=1").QueryObj(obj)
// 导出 id 为 1 的数据，并回填到 user 实例中
user := &User{Id:1}
err := e.Select(u)
```
其中的e是什么, 有没有完整的例子




如果e传参用db2 
```
 err,_:=sqlbuilder.Select(db2).Columns("*").From("user").Where("id=1").QueryObject(true,obj)
 
``` 
会报错 
cannot use sqlbuilder.Select(db2).Columns("*").From("user").Where("id=1").QueryObject(true, obj) (value of type int) as type error in assignment:
        int does not implement error (missing Error method)

**Comment by caixw** [comment]
ows, err := db2.Query(sql,[]interface{}{1})
这个写法现在不行了，应该是文档还没有改过来。

e 表示的是 [core.Engine](https://pkg.go.dev/github.com/issue9/orm/v5@v5.1.0/core#Engine)， [DB](https://pkg.go.dev/github.com/issue9/orm/v5#DB) 和 [Tx](https://pkg.go.dev/github.com/issue9/orm/v5#Tx) 都实现了这个接口。
QueryObject 返回的两个参数，其中第一个表示实际查询到的数量，第二个表示错误信息。


文档直接看 <https://pkg.go.dev/github.com/issue9/orm/v5>，自己写的那个没有及时更新上。
